name: 'Stylus to Firemonkey'
description: 'A Github action for converting Stylus scripts into ones that can be used by Firemonkey.'
author: 'Nino Maruszewski'
inputs:
  styles:
    required: true
    description: 'A list or a file containing Stylus style urls to process.'
  debug-only:
    required: false
    description: Run the workflow as a dry-run
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
