name: "Dependabot Automerge"

on:
  pull_request_target:

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # - name: automerge
      #   uses: actions/github-script@v4
      #   with:
      #     script: |
      #       github.pulls.createReview({
      #         owner: context.payload.repository.owner.login,
      #         repo: context.payload.repository.name,
      #         pull_number: context.payload.pull_request.number,
      #         event: 'APPROVE',
      #         body: "@dependabot merge"
      #       })
      #     github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
